config/routes.rb
Rails.application.routes.draw do
  get 'users/profiles', to: 'users#profiles', as: :top
  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  post '/users/sign_in', to: 'users#sign_in_process'
  get '/users/sign_out', to: 'users#sign_out', as: :sign_out
  get '/users/sign_up', to: 'users#sign_up', as: :sign_up

  
  get '/products', to: 'products#products', as: :products
  get '/products/new', to: 'products#new', as: :new
  get '/products/(:id)', to: 'products#show', as: :product
  get '/products/(:id)/like', to: 'products#like', as: :product_like
  get '/products/(:id)/edit', to: 'products#edit', as: :product_edit
  post '/products/(:id)/edit', to: 'products#update'
  post '/products', to: 'products#create'
  delete '/products/(:id)', to: 'products#destroy'

  
  get '/users/likes', to: 'users#likes', as: :likes
  get '/users/profiles/edit', to: 'users#edit', as: :profiles_edit
  post '/users/sign_up', to: 'users#sign_up_process'
  post '/users/profiles/edit', to: 'users#update'
  get '/', to: 'users#total', as: :total
  
  get 'markets/(:id)', to:'markets#item', as: :item
  get 'markets/(:id)/payment', to: 'markets#payment', as: :payment
  post 'markets/(:id)/payment', to: 'markets#purchase'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    before_create :convert_password
    has_many :products
    has_many :userlikes
    
    def convert_password
        self.password = User.generate_password(self.password)
    end
    def self.generate_password(password)
        salt = "h!hgamcRAdh38bajhvgai17ysvb"
        Digest::MD5.hexdigest(salt + password)
    end
    
    # バリデーション
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name, presence: true
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
    validates :password, presence: true, length:{minimum: 8}, confirmation: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:sign_up, :sign_up_process, :sign_in, :sign_in_process]
  before_action :redirect_to_top_if_signed_in, only: [:sign_up, :sign_in]
  
  def profiles
    @user = current_user
    @product = Product.where(user_id: @user.id)
  end
  
  def edit
      @user = current_user
  end
  
  def update
    @user = current_user
    upload_file = params[:user][:image]
    if upload_file.present?
      upload_file_name = upload_file.original_filename
      output_dir = Rails.root.join('public', 'users')
      output_path = output_dir + upload_file_name
      File.open(output_path, 'w+b') do |f|
        f.write(upload_file.read)
      end
      @user.image =  upload_file.original_filename
    end
    if user_params[:password].length > 0
      @user.update(user_params)
    else
      @user.update(update_params)
    end
    p current_user.errors.full_messages
    # データベースに更新
    redirect_to top_path and return
  end
  
  
  
  def sign_in
    @user = User.new
    render layout: "application_search"
  end
  
  def sign_in_process
    password_md5 = User.generate_password(user_params[:password])
    user = User.find_by(email: user_params[:email], password: password_md5)
    if user
      user_sign_in(user)
      redirect_to top_path and return
    else
      # flash[:danger] = "サインインに失敗しました。"
    end
  end
  
  def sign_up
    @user = User.new
    render layout: "application_search"
  end
  
  def sign_up_process
    user = User.new(user_params)
    if user.save
      user_sign_in(user)
      redirect_to profiles_path and return
    else
      flash[:danger] = "入力に不備があります。"
      redirect_to sign_up_path and return
    end
  end
  
  def sign_out
    user_sign_out
    redirect_to sign_in_path and return
  end
  
  def user_sign_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def likes
    @user = current_user
    
    @products = Product.where(id: Userlike.where(user_id: @user.id).pluck(:product_id))
  end
  
  def total
    @product = Product.all
    if params[:word].present?
      @product = @product.where("name like ?", "%#{params[:word]}%")
    end
    
    if params[:category_id].present?
      if params[:category_id] == "5"
        @product = @product.all
      else
        @product = @product.where(category_id: params[:category_id])
      end
    end
    
    if params[:min_price].present?
      @product = @product.where("price >= ?", params[:min_price].to_i)
    end
    
    if params[:max_price].present?
      @product = @product.where("price <= ?", params[:max_price].to_i)
    end
    
    if params[:arrangement] == "created_at"
      if params[:order] == "asc"
        @product = @product.order("created_at asc")
      elsif params[:order] == "desc"
        @product = @product.order("created_at desc")
      end
     elsif params[:arrangement] =- "price" 
      if params[:order] == "asc"
        @product = @product.order("price asc")
      elsif params[:order] == "desc"
        @product = @product.order("price desc")
      end
    end
    render layout: "application_search"
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile)
  end
  
  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id).merge(user_id: current_user.id)
  end
  
  def update_params
    params.require(:user).permit(:name, :email, :profile)
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def user_sign_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        if @current_user.nil?
            @current_user = User.find_by(id: session[:user_id])
        else
            @current_user
        end 
    end
    
    def user_signed_in?
        current_user.present?
    end
    
    def authorize
        redirect_to sign_in_path unless user_signed_in?
    end
    
    def redirect_to_top_if_signed_in
        redirect_to top_path and return if user_signed_in?
    end
    
    def image_url(user)
        if user.image.blank?
            "https://dummyimage.com/200x200/000/fff"
        else
            "/users/#{user.image}"
        end
    end
end

app/views/users/_mypage.html.erb
<!--<div>-->
<!--    <h2>マイページ</h1>-->
<!--    <%= link_to "出品する", new_path %>-->
<!--    <%= link_to "お気に入りの商品", likes_path %>-->
<!--    <%= link_to "プロフィール更新", profiles_edit_path &>-->
<!--    <%= link_to "サインアウト", sign_out_path %>-->
<!--</div>-->

app/views/users/edit.html.erb
<div>
  <%= form_for @user, url: profiles_edit_path, method: :post do |f| %>
    
    <label>画像</label>
        <%= f.file_field :image %>
        
    
    <%= f.label :name, "名前" %>
    <%= f.text_field :name, placeholder: "名前を入力して下さい。", value: @user.name %>
    
    <%= f.label :profile, "プロフィール" %>
    <%= f.text_field :profile, placeholder: "コメントを入力して下さい。", value: @user.profile %>
    
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, placeholder: "パスワードを更新しない場合は入力しないで下さい" %>
    
    <%= f.label :password_confirmation, "パスワード確認用" %>
    <%= f.password_field :password_confirmation, placeholder: "確認用" %>
    
    <input type="submit" value="保存する">
        
  <% end %>
</div>

app/views/users/likes.html.erb
<ul>
    <% if @products.any? %>
        <% @products.each do |product| %>
        <li>
            <%= link_to product_path(product) do %>
                <%= image_tag "/images/#{product.image1}" if product.image1.present? %>
            <% end %>
            
            <p><%= product.name %></p>
            <p>¥<%= product.price %></p>
            <%= link_to product_like_path(product) do %>
                <i class="fa <%= product.like_from?(current_user)? "fa-heart active" : "fa-heart-o" %>"></i>
            <% end %>
        </li>
        <% end %>
    <% else %>
        <p>お気に入りの商品は見つかりませんでした。</p>
    <% end %>
</ul>

app/views/users/profiles.html.erb
<div>
  <div style="background: url('<%= image_url(@user) %>'); background-position: 50%; background-size: cover;"></div>
</div>
<%= image_tag "/users/#{@user.image}" if @user.image.present? %>
<p><%= @user.name %>さん</p>
<p>出品数<%= @product.name.length %></p>

<%= @user.profile %>

app/views/users/sign_in.html.erb
<div>
    <h2>メールアドレス</h2>
    <%= form_for @user, url: sign_in_path do |f| %>
        <%= f.email_field :email, placeholder: "tarou@test.com" %>
    <h2>パスワード</h2>
        <%= f.password_field :password, placeholder: "8文字以上の英数字" %>
    <button>サインインする</button>
    <% end %>
    <p>アカウントをお持ちですか？<%= link_to "新規登録する", sign_up_path %></p>
</div>

app/views/users/sign_up.html.erb
<div>
    <%= form_for @user, url: sign_up_path do |f| %>
    <h2>ニックネーム</h2>
    <%= f.text_field :name, placeholder: "太郎" %>
    <h2>メールアドレス</h2>
    <%= f.email_field :email, placeholder: "test@test.com" %>
    <h2>パスワード</h2>
    <%= f.password_field :password, placeholder: "8文字以上の英数字" %>
    <h2>パスワード（確認）</h2>
    <%= f.password_field :password_confirmation, placeholder: "確認" %>
    <button>登録する</button>
    <% end %>
</div>
<div>
    <p>アカウントをお持ちですか？<%= link_to "サインインする" ,sign_in_path %></p>
</div>

app/views/users/total.html.erb
<ul>
    <% if @product.any? %>
        <% @product.each do |product| %>
        <li>
            <%= link_to product_path(product) do %>
                <%= image_tag "/images/#{product.image1}" if image1.present? %>
            <% end %>
            <p><%= product.name %></p>
            <p><%= product.price %></p>
            <%= link_to like_path(product) do %>
                <i class="fa <%= product.like_from?(current_user)? "fa-heart active" : "fa-heart-o" %>"></i>
            <% end %>
        </li>
        <% end %>
    <% else %>
        <p>対象の商品は見つかりませんでした。</p>
    <% end %>
</ul>