config/routes.rb
Rails.application.routes.draw do
  get 'users/profiles', to: 'users#profiles', as: :top
  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  post '/users/sign_in', to: 'users#sign_in_process'
  get '/users/sign_out', to: 'users#sign_out', as: :sign_out
  get '/users/sign_up', to: 'users#sign_up', as: :sign_up

  
  get '/products', to: 'products#products', as: :products
  get '/products/new', to: 'products#new', as: :new
  get '/products/(:id)', to: 'products#show', as: :product
  get '/products/(:id)/like', to: 'products#like', as: :product_like
  get '/products/(:id)/edit', to: 'products#edit', as: :product_edit
  post '/products/(:id)/edit', to: 'products#update'
  post '/products', to: 'products#create'
  delete '/products/(:id)', to: 'products#destroy'

  
  get '/users/likes', to: 'users#likes', as: :likes
  get '/users/profiles/edit', to: 'users#edit', as: :profiles_edit
  post '/users/sign_up', to: 'users#sign_up_process'
  post '/users/profiles/edit', to: 'users#update'
  get '/', to: 'users#total', as: :total
  
  get 'markets/(:id)', to:'markets#item', as: :item
  get 'markets/(:id)/payment', to: 'markets#payment', as: :payment
  post 'markets/(:id)/payment', to: 'markets#purchase'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
    def item
        @product = Product.find(params[:id])
        @category = Category.find(@product.category_id)
        render layout: "application_search"
    end
    
    def payment
        @product = Product.find(params[:id])
        render layout: "application_search"
    end
    
    def purchase
        @product = Product.find(params[:id])
        # @product.status = 1
        @product.update(status: 1)
        redirect_to total_path and return
    end
    
    private
    def product_params
        params.require(:product).permit(:name, :description, :price,  :image1, :image2, :image3).merge(user_id: current_user.id)
        # :category_id,
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/item.html.erb
<div>
    <p><%= @product.name %></p>
</div>    
<div>
    <%= image_tag "/images/#{@product.image1}" if @product.image1.present? %>
</div>
<div>
    <%= image_tag "/images/#{@product.image2}" if @product.image2.present? %>
</div>    
<div>
    <%= image_tag "/images/#{@product.image3}" if @product.image3.present? %>
</div>    
<div>
    <p>カテゴリー:<%= @category.name %></p>
</div>
<div>
    <p>￥<%= @product.price %></p>
</div>
<div>
    <% if @product.status == 0 %>
        <%= link_to "購入する", payment_path(@product) %>
    <% end %>
</div>
<div>
    <%= @product.description %>
</div>

app/views/markets/payment.html.erb
<div>
    <div>
        <p><%= @product.name %></p>
    </div>    
    <div>
        <%= image_tag "/images/#{@product.image1}" if @product.image1.present? %>
    </div>    
    <div>
        <p>￥<%= @product.price %></p>
    </div>
    <div>
        <%= button_to "購入を確定する" %>
    </div>
</div>