config/routes.rb
Rails.application.routes.draw do
  get 'users/profiles', to: 'users#profiles', as: :top
  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  post '/users/sign_in', to: 'users#sign_in_process'
  get '/users/sign_out', to: 'users#sign_out', as: :sign_out
  get '/users/sign_up', to: 'users#sign_up', as: :sign_up

  
  get '/products', to: 'products#products', as: :products
  get '/products/new', to: 'products#new', as: :new
  get '/products/(:id)', to: 'products#show', as: :product
  get '/products/(:id)/like', to: 'products#like', as: :product_like
  get '/products/(:id)/edit', to: 'products#edit', as: :product_edit
  post '/products/(:id)/edit', to: 'products#update'
  post '/products', to: 'products#create'
  delete '/products/(:id)', to: 'products#destroy'

  
  get '/users/likes', to: 'users#likes', as: :likes
  get '/users/profiles/edit', to: 'users#edit', as: :profiles_edit
  post '/users/sign_up', to: 'users#sign_up_process'
  post '/users/profiles/edit', to: 'users#update'
  get '/', to: 'users#total', as: :total
  
  get 'markets/(:id)', to:'markets#item', as: :item
  get 'markets/(:id)/payment', to: 'markets#payment', as: :payment
  post 'markets/(:id)/payment', to: 'markets#purchase'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :userlikes
  
  def like_from?(user)
    self.userlikes.exists?(user_id: user.id)
  end
  
  # def initialize(params)
  #   @user_name = params[:name]
  #   @image1 = params[:image1]
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authorize
    def products
        if params[:word].present?
            @product = Product.where("description like ?", "%#{params[:word]}%").order("id desc")
        else
            @product = Product.all.order("id desc")
        end
    end
  
    def show
        @product = Product.find(params[:id])
        @category = Category.find(@product.category_id)
    end
  
    def edit
        @user = current_user
        @product = Product.find(params[:id])
        @category = Category.all
    end
    
    def update
        upload_file = params[:product][:image1]
        if upload_file.present?
            upload_file_name = upload_file.original_filename
            output_dir = Rails.root.join('public', 'images')
            output_path = output_dir + upload_file_name
            File.open(output_path, 'w+b') do |f|
                f.write(upload_file.read)
            end
            current_user.update(product_params.merge({image: upload_file.original_filename}))
        else
            current_user.update(product_params)
        end
   
    redirect_to top_path and return
    end
    
    def new
       @product = Product.new
       @category = Category.all
    end
    
    def create
        @product = Product.new(product_params)
        @product.status = 0
        # upload_file = params[:product][:upload_file]
        upload_file1 = params[:product][:image1]
        file_name = image_edit(upload_file1)
        if file_name.nil?
            flash[:danger] = "出品には画像が必須です。"
            redirect_to new_path and return
        end
        @product.image1 = file_name
        
        upload_file2 = params[:product][:image2]
        file_name = image_edit(upload_file2)
        @product.image2 = file_name if file_name.present?
        
        upload_file3 = params[:product][:image3]
        file_name = image_edit(upload_file3)
        @product.image3 = file_name if file_name.present?
        
        
        
        # if upload_file.blank?
        #     flash[:danger] = "出品には画像が必須です。"
        #     redirect_to new_path and return
        # else
        #     upload_file_name = upload_file.original_filename
        #     output_dir = Rails.root.join('public', 'images')
        #     output_path = output_dir + upload_file_name
        #     puts output_dir
        #     puts upload_file_name
        #     File.open(output_path, 'w+b') do |f|
        #         f.write(upload_file.read)
        #     end
        #     @product[:image1] = upload_file_name
        # end
        
        # @product = Product.new(image1: upload_file_name)
        if @product.save
            redirect_to :products
            flash[:success] = "出品しました。"
        else
            redirect_to :new
            flash[:danger] = "出品に失敗しました。"
        end
    end
    
    def destroy
        @product= Product.find(params[:id])
        # @product= Product.find(current_user.id)
        if @product.destroy
            redirect_to top_path
            flash[:success] = "投稿を削除しました。"
        else
            redirect_to top_path
            flash[:danger] = "削除に失敗しました。"
        end 
    end
    
    def like
        @product = Product.find(params[:id])
        if Userlike.exists?(product_id: @product.id, user_id: current_user.id)
          Userlike.find_by(product_id: @product.id, user_id: current_user.id).destroy
        else
          Userlike.create(product_id: @product.id, user_id: current_user.id)
        end
        redirect_to total_path and return
    end
    
    private
    def product_params
        params.require(:product).permit(:name, :description, :price, :category_id, :status, :image1, :image2, :image3).merge(user_id: current_user.id)
    end
    
    def image_edit(upload_file)
        if upload_file.blank?
            return nil
        else
            upload_file_name = upload_file.original_filename
            output_dir = Rails.root.join('public', 'images')
            output_path = output_dir + upload_file_name
            puts output_dir
            puts upload_file_name
            File.open(output_path, 'w+b') do |f|
                f.write(upload_file.read)
            end
            return upload_file_name
        end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
    
    # def current_user
    #     if @current_user.nil?
    #         @current_user = User.find_by(id: session[:user_id])
    #     else
    #         @current_user
    #     end 
    # end
    
end

app/views/products/edit.html.erb
<div>
<%= form_for @product do |f| %>
  <div>
    <div>
        <p>商品名</p>
        <%= f.text_area :name, value: @product.name %>
    </div>
    <div>
        <p>説明</p>
        <%= f.text_area :description, value: @product.description %>
    </div>
    <div>
        <p>カテゴリー</p>
        <%= f.collection_select :category_id, @category, :id, :name %>
    </div>
    <div>
        <p>価格</p>
        <%= f.number_field :price , value: @product.price %>
    </div>
    
    <div>
        <p>画像１</p>
        <%= f.file_field :image1 %> 
        <%= image_tag "/images/#{@product.image1}" if @product.image1.present? %>
    </div>
    <div>
        <p>画像２</p>
        <%= f.file_field :image2 %> 
        <%= image_tag "/images/#{@product.image2}" if @product.image2.present? %>
    </div>
    <div>
        <p>画像３</p>
        <%= f.file_field :image3 %> 
    </div>
  </div>
  <div>
    <%= f.submit "送信する" %>
  </div>
<% end %>
</div>

app/views/products/new.html.erb
<div>
<%= form_for @product do |f| %>

  <div>
    <div>
        <p>商品名</p>
        <%= f.text_area :name, placeholder: "Tシャツ", value: @product.name %>
    </div>
    <div>
        <p>説明</p>
        <%= f.text_area :description, placeholder: "オリジナルTシャツです" , value: @product.description %>
    </div>
    <div>
        <p>カテゴリー</p>
        <%= f.collection_select :category_id, @category, :id, :name %>
    </div>
    <div>
        <p>価格</p>
        <%= f.number_field :price , value: 0 %>
    </div>
    <div>
        <p>画像１</p>
        <%= f.file_field :image1,value: @product.image1 %> 
    </div>
    <div>
        <p>画像２</p>
        <%= f.file_field :image2 %> 
    </div>
    <div>
        <p>画像３</p>
        <%= f.file_field :image3 %> 
    </div>
  </div>
  <div>
    <%= f.submit "送信する" %>
  </div>
<% end %>
</div>

app/views/products/products.html.erb
<div>
    <% if @product.any? %>
    <ul>
        <% @product.each do |product| %>
            <li>
                <div>
                    <%= link_to product_path(product) do %>
                        <%= image_tag "/images/#{product.image1}" if product.image1.present? %>
                    <% end %>
                    <%= link_to product_path(product) do %>
                        <%= image_tag "/images/#{product.image2}" if product.image2.present? %>
                    <% end %>
                    <%= link_to product_path(product) do %>
                        <%= image_tag "/images/#{product.image3}" if product.image3.present? %>
                    <% end %>
                    <br>
                    <%= product.name %>
                    <br>
                    <p>￥<%= product.price %></p>
                </div>
            </li>
        <% end %>
    </ul>
    <% else %>
        <p>投稿がありません。</p>
    <% end %>
</div>

app/views/products/show.html.erb
<div>
<% if @product.user_id == current_user.id %>
  <% if @product.status == 0 %>
    <p>販売中</p>
  <% else %>
    <p>売り切れ</p>
  <% end %>
  <p><%= @product.name %></p>
  
  <%= image_tag "/images/#{@product.image1}" if @product.image1.present? %>
  <%= image_tag "/images/#{@product.image2}" if @product.image2.present? %>
  <%= image_tag "/images/#{@product.image3}" if @product.image3.present? %>
  
  <p>カテゴリー:<%= @category.name %></p>
  <p>￥<%= @product.price %></p>
  <p>販売手数料(10%)¥<%= @product.price * 0.1 %></p>
  <p>販売利益¥<%= @product.price * 0.9 %></p>
  <%= link_to "編集する",product_edit_path(@product) %>
  <p><%= @product.description %></p>
  
    <%= link_to product_path(@product), method: :delete do %>
      <i class="fa fa-close"></i>
    <% end %>
  削除する
  カテゴリーname
  
<% else %>
  
<% end %>
</div>