config/routes.rb
Rails.application.routes.draw do
  get 'users/profiles', to: 'users#profiles', as: :top
  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  post '/users/sign_in', to: 'users#sign_in_process'
  get '/users/sign_out', to: 'users#sign_out', as: :sign_out
  get '/users/sign_up', to: 'users#sign_up', as: :sign_up

  
  get '/products', to: 'products#products', as: :products
  get '/products/new', to: 'products#new', as: :new
  get '/products/(:id)', to: 'products#show', as: :product
  get '/products/(:id)/like', to: 'products#like', as: :product_like
  get '/products/(:id)/edit', to: 'products#edit', as: :product_edit
  post '/products/(:id)/edit', to: 'products#update'
  post '/products', to: 'products#create'
  delete '/products/(:id)', to: 'products#destroy'

  
  get '/users/likes', to: 'users#likes', as: :likes
  get '/users/profiles/edit', to: 'users#edit', as: :profiles_edit
  post '/users/sign_up', to: 'users#sign_up_process'
  post '/users/profiles/edit', to: 'users#update'
  get '/', to: 'users#total', as: :total
  
  get 'markets/(:id)', to:'markets#item', as: :item
  get 'markets/(:id)/payment', to: 'markets#payment', as: :payment
  post 'markets/(:id)/payment', to: 'markets#purchase'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flea</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>

  <body>
    <header class="header">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>"><%= message %></div>
      <% end %>
      <div class="container clearfix">
        <h1 class="logo_title">Flea Market</h1>
        <%= form_tag total_path ,method: :get ,class: "search_box" do %>
          <%= text_field nil, :word, placeholder: "キーワードから検索" %>
          <%= button_tag do %>
            <i class="fab fa-sistrix"></i>
          <% end %>
        <% end %>
        <!--出品ボタン-->
        <div class="exhibit_button">
          <%= link_to "出品する",new_path,class: "box_character" %>
        </div>
        <%= link_to products_path do %>
          <span class="icon_size"></span>
          
        <% end %>
      </div>
    </header>
    <main>
      <div class="container clearfix">
        <div class="yield">
          <%= yield %>
        </div>
        <nav class="my_page">
          <h1 class="my_page_title">マイページ</h1>
          <ul>
            <li><%= link_to "出品する", new_path %></li>
            <li><%= link_to "出品中の商品", products_path %></li>
            <li><%= link_to "お気に入りの商品", likes_path %></li>
            <li><%= link_to "プロフィール更新", profiles_edit_path %></li>
            <li><%= link_to "サインアウト", sign_out_path %></li>
          </ul>
        </nav>
      </div>
    </main>
    <footer>
      <div class="container clearfix">
        <ul class="clearfix">
          <li>プライバシーポリシー</li>
          <li>特定商取引に基づく表示</li>
          <li>利用規約</li>
          <li>サイトマップ</li>
        </ul>
      </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
      window.setTimeout(function() {
        $(".alert").slideUp();
      }, 3000);
    </script>
  </body>
</html>

app/views/layouts/application_search.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>

<body>
    <header class="header">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>"><%= message %></div>
      <% end %>
      <div class="container clearfix">
        <h1 class="logo_title">Flea Market</h1>
        <form class="search_box">
          <input type="text" placeholder="キーワードから検索" name="word" value="">
          <%= link_to products_path do %>
            <i class="fab fa-sistrix"></i>
          <% end %>
        </form>
        <div class="exhibit_button">
          <%= link_to "出品する",new_path,class: "box_character" %>
        </div>
        <%= link_to products_path do %>
          <span class="icon_size"></span>
        <% end %>
      </div>
    </header>
    <main>
      <div class="container clearfix">
        <div class="yield">
          <%= yield %>
        </div>
        <nav class="extensive_search">
        <h1>詳細検索</h1>
        <%= form_tag total_path ,method: :get do %>
        <div>
            <div class="search_margin">
                <p>キーワード追加</p>
                <%= text_field nil, :word, placeholder: "例) 値下げ" %>
            </div>
            <div class="search_margin">
                <p>カテゴリー選択</p>
                <%= collection_select nil, :category_id, Category.all, :id, :name %>
            </div>
            <div class="search_margin">
                <p>価格</p>
                <%= number_field nil, :min_price , value: 100 ,class: "price_box" %>
                <p>〜</p>
                <%= number_field nil, :max_price , value: 1000 ,class: "price_box" %>
            </div>
            <div class="search_margin">
                <p>並び替え</p>
                <%= select nil, :arrangement, {"新着順" => "created_at", "価格順" => "price"} %>
                <%= select nil, :order, {"昇順" => "asc", "降順" => "desc"} %>
            </div>
            <div class="search_margin">
                <%= submit_tag "検索" %>
            </div>
        </div>
        <% end %>
        </nav>
        </div>
    </main>
    <footer>
      <div class="container clearfix">
        <ul class="clearfix">
          <li>プライバシーポリシー</li>
          <li>特定商取引に基づく表示</li>
          <li>利用規約</li>
          <li>サイトマップ</li>
        </ul>
      </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
      window.setTimeout(function() {
        $(".alert").slideUp();
      }, 3000);
    </script>
</body>
</html>